sudo: false
language: python
python:
  - 2.6
  - 2.7
  - 3.4
  - 3.5

cache: pip
# command to install dependencies
install: 
  - python setup.py install --user
  - pip install -U pytest
# # command to run tests
script:
  - py.test .
