version: '{branch}-{build}'
build: off
cache:
  - '%LOCALAPPDATA%\pip\Cache'
install:
  - pip install nose mock
  - pip install .
on_success:
  - python -m nose -v
on_failure:
  - ps: dir "env:"
notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    on_build_failure: true